Show_message_bubbles:
  type: bool
  default: true
  description: 'Show messages in speech bubbles'

Your_message_bubble_color:
  type: string
  default: green
  description: 'Enter a background color for <b>your</b> messages, sent from you.<br> Colors can be by name e.g. blue, green red, yellow, black, white<br>You can also enter primary, secondary, tertiary and quaternary to match your theme color settings.<br>For FIXED colors you can also enter a html code e.g. #0066CC. PLEASE NOTE you must set the opacity to 100% if using the html color codes.'


Other_message_bubble_color:
  type: string
  default: blue
  description: 'Enter a background color for <b>other</b> messages, sent to you.<br>This helps dintinguish between messages sent and received.<br>See the instructions above on how to enter the colors and color codes.'

Your_message_text_color:
  type: string
  default: primary
  description: 'The text color in the message bubbles sent from you.<br>Enter primary or secondary to match your light and dark theme.<br>You can also enter color names or html color codes e.g. as above.'

Other_message_text_color:
  type: string
  default: primary
  description: 'The text color in the message bubbles sent to you.'

Message_bubble_opacity:
  type: enum
  default: 10%
  choices:
    - 5%
    - 10%
    - 15%
    - 20%
    - 25%
    - 50%
    - 75%
    - 100%
  description: 'Select the opacity of the message background color. The larger the percentage the deeper the color<br>The bubble color is blended with the theme background color. This enables the color to adjust to light and dark theme settings.<br>PLEASE NOTE when usimg html color codes (e.g. #00FF00) you must set the opacity to 100%'

Show_box_border:
  type: bool
  default: true
  description: 'Show a box border on the message bubbles' 
  
Show_box_shadow:
  type: bool
  default: true
  description: 'Show a box shadow on the message bubbles' 
  
Message_button_added_text:
  type: string
  default: ''
  description: 'Text to be appended to "Reply" button'

